<?php

namespace Codeex\RoleAssignment\Models;

use App\Traits\ResourceMaker;
use Illuminate\Database\Eloquent\Model;

class Msp extends Model
{
    use ResourceMaker;

    static public $resource_code = 'msp';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

}
