<?php

namespace Codeex\RoleAssignment\Models;

use App\Traits\ResourceMaker;
use Illuminate\Database\Eloquent\Model;

class Msp extends Model
{
    use ResourceMaker;

    static public $resource_code = 'msp';

    protected $hidden = ['id'];

    protected $fillable = [
        'logo', 'domain', 'email', 'name'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function accounts(){
        return $this->hasMany(Account::class, 'msp_id', 'id');
    }

}
