<?php

namespace Codeex\RoleAssignment\Models;

use App\Traits\ResourceMaker;
use Illuminate\Database\Eloquent\Model;

class Resource extends Model
{
    use ResourceMaker;

    protected $fillable = [
        'resource_code', 'name', 'description'
    ];

    static public $resource_code = 'resource';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

}
